export const AUTH_REQ = 'AUTH_REQ';
export const AUTH_REQ_SUCCESS = 'AUTH_REQ_SUCCESS';
export const AUTH_REQ_FAILURE = 'AUTH_REQ_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
